screen:
  size: !tup [1100, 650]
  title: "Numerical Methods"
  resizable: false
  icon: "icon.png"

color:
  background:  !tup [30, 30, 30]
  text:  !tup [0, 0, 0]

font:
  scale: !tup [1, 1.5]
  size: 20